zaptayfresh/ZaptayNew/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),  #id :- lucky pwd :- lucky
    path('zaptay-admin-login/', include('admin_login.urls')),
    path('seller-login/', include('seller_login.seller_urls')),

    path('', include('home.urls')),
    path('user/', include('user_login.user_login_urls')),
    #############################    SMTP  ####################################
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name='smtp_template/password_reset.html'), name='reset_password'),
    
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name='smtp_template/password_reset_sent.html'),name='password_reset_done'),

    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='smtp_template/set_password.html'),name='password_reset_confirm'),
    
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='smtp_template/password_reset_done.html'),name='password_reset_complete'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zaptayfresh/home/urls.py
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from .import views

app_name = 'home'

urlpatterns = [

    
    path('', views.MainHome.as_view(), name="homepage"),
    path('singleproduct/<slug:Product_iD>',views.singleProduct.as_view(),name="singleproduct"),
    path('subcategory/<uuid:sucat_id>',views.SubCategoryProductView.as_view(),name="subcategory"),
    path('Indianhatt/',views.IndianHatt.as_view(),name="indianHatt"),
    path('b2b/', views.b2b.as_view(), name="b2b"),
    path('update_item/',views.updateItem,name='update_item'),
    path('cart/',views.cart,name='cart'),


    #LOGIN
    path('ShowuserLogin/', views.ShowuserLogin,name="user_loginpage"),
    # path('ShowuserSignup/', views.ShowuserSignup.as_view() ,name="user_signuppage"),  #login/
    path('ShowuserSignup/', views.ShowuserSignup,name="user_signuppage"),
    path('user_logout/', views.user_Logout, name="user_logout"),  # logout/
    path('ResetPwd/', views.ResetPwd.as_view(), name="ResetPwd"),
    path('activate/<uidb64>/<token>/',views.Verificationview.as_view(),name="activate"),
    

    path('vieall/<slug:name>',views.viewall.as_view(),name="viewall"),
    path('vieallSubCat/<slug:name>',views.viewallSubCategory.as_view(),name="viewallSuCat"),
    # path('wish-list/', include('wishlist.urls')),
    # path('cart-list/', include('cart.urls')),

   ########  for  shopping cart ########
  

    # Ajax
    # Views Counter
    path('customerView/', views.CustomerView, name="CustomerView"),

    # home page
    path('bannerjson/', views.bannerJasonList.as_view(), name="bannrjson"),
    path('bannerjsonspecific/',views.bannerJasonListspecific,name="bannerjsonspecific"),


    #single prod page
    path('relatedProdSingleProdpage/',views.relatedProdSingleProdpage,name="relatedProdSingleProdpage"),
    path('PODSingleProdpage/',views.PODSingleProdpage,name="PODSingleProdpage"),

    


    #sub category page
    path('underTer/',views.underTerAll.as_view(),name="underTer"),
    path('underTerspecific/',views.underTerspecific,name="underTerspecific"),
    path('allprod/',views.allproduct,name="allprod"),
    path('getprodbyBrand/',views.getprodbyBrand,name="getprodbyBrand"),
    path('getprodbySize/',views.getprodbySize,name="getprodbySize"),
    path('getprodbycolor/',views.getprodbycolor,name="getprodbycolor"),
    path('underTerprod/', views.underTerprod, name="underTerprod"),

    path('underTerprod/', views.underTerprod, name="underTerprod"),
    path('underTerprod/', views.underTerprod, name="underTerprod"),

    path('relatedProdSubCatpage/',views.relatedProdSubCatpage,name="relatedProdSubCatpage"),
    path('PODSubCatpage/',views.PODSubCatpage,name="PODSubCatpage"),


    #indian hatt
    path('Ihatttwntyprsnt/', views.Ihatttwntyprsnt, name="Ihatttwntyprsnt"),
    path('b2b/', views.b2b, name="b2b"),

    # view all offer
    path('viewall_offer/', views.viewalloffersMore, name="viewall_offer"),
    path('viewallofferscolFilter/', views.viewallofferscolFilter, name="viewallofferscolFilter"),
    # view all Subcat
    path('viewall_Subcat/', views.viewallSubcatMore, name="viewall_Subcat"),
    path('viewallSubcatcolrFilter/', views.viewallSubcatcolrFilter, name="viewallSubcatcolrFilter"),
    
    


]

 

zaptayfresh/user_login/models.py
from django.db import models

# Create your models here.

zaptayfresh/user_login/views.py
from django.shortcuts import render
from django.views.generic import *


# Models Import
from banner.models import *
from offer.models import *
from attribute.models import *
from zap_product.models import *
# Models Import End




# Create your views here.



class LoginView(TemplateView):
    template_name = "user_templates/user_login/user_login.html"


    def get_context_data(self, **kwargs):
        Offers_all = Offer.objects.all()
        produ = Productmod.objects.all()

        subCat = SubCategory.objects.all()
        terCat = TertiaryCategory.objects.all()
        # print(Offers_all)
        # print(subCat)
        # print(terCat)
        # for i in terCat:
        #     print(i.sub_category_id.sub_category_name)
        banners_head = webLogo.objects.filter(banner_name='header_logo').first()



        context = {
            'offers': Offers_all,
            'product': produ,
            'Subcat': subCat,
            'Tercat': terCat,
            'baner_head': banners_head,

        }
        return context





class SignupView(TemplateView):
    template_name = "user_templates/user_login/user_signup.html"

    def get_context_data(self, **kwargs):
        Offers_all = Offer.objects.all()
        produ = Productmod.objects.all()

        subCat = SubCategory.objects.all()
        terCat = TertiaryCategory.objects.all()
        # print(Offers_all)
        # print(subCat)
        # print(terCat)
        # for i in terCat:
        #     print(i.sub_category_id.sub_category_name)
        banners_head = webLogo.objects.filter(
            banner_name='header_logo').first()

        context = {
            'offers': Offers_all,
            'product': produ,
            'Subcat': subCat,
            'Tercat': terCat,
            'baner_head': banners_head,
        }
        return context

zaptayfresh/templates/user_templates/user_login/activate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Sent</title>
                        <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-7SLCSNT7XT"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7SLCSNT7XT');
</script>



    <link rel="icon" href="images/favicon1.png">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">
    <style>

        html{
            display: flex;
            align-items: center;
            justify-content: center;
            font-family: poppins;
            font-weight: 600;
        }
        body, p{
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
        }
        .message{
            width: 50vw;
            font-size: 21px;
        }
        img{
            width: 400px;
        }
        .salutation{
            font-size: 50px;
            margin: 20px;
            display: inline;
        }
        @media only screen and (max-width: 500px){
            .message{
                font-size: 18px;
            }
        }

    </style>
</head>
<body>
    <p class="salutation">Hi<span style="color: #f9912e; display: inline;">.</span></p>
    <center><p class="message"></p></center>
    <h> Succesfully registered as a user , please confirm your email to Login</h>
    <h3>Note : Please also check in spam folders</h3>
   <br>
    <img src="{% static 'images/activateaccount.png' %}">    
    <br>
    <br>
    
</body>

</html> 

zaptayfresh/templates/user_templates/user_login/failauth.html
authentication failed! try again
<button onclick="location.href='/ShowuserLogin/'" class="btn btn-primary font-weight-light" style="font-size: 16px; letter-spacing: 0px; padding: -1;">Login</button>

zaptayfresh/templates/user_templates/user_login/user_login.html
{% extends "user_templates/base_user.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block add_css %}
<link rel="stylesheet" href="/static/css/user-side-CSS/user_login/login.css">
{% endblock %}


{% block content %}
<div class="container">
  <div class="login_form_section">
    <div class="login_form_div">
      <h4 class="text-primary">Log In to your Zaptay Account</h4>
      <hr />
      <!-- <button type="button" class="btn btn-primary">Primary</button> -->
      <div class="login_form">
        <!--  -->




               <h2 class="text-danger text-center">{{db_error}}</h2> 
        <form method="POST" action="{% url 'home:user_loginpage' %}">
          {% csrf_token %}
              {{error4}}{{not_match}}
          <div class="alert alert-danger alert-dismissible fade" role="alert">
            <strong class="error_title">Holy guacamole!</strong> <span class="error_message"></span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="far fa-envelope"></i></div>
            </div>
            <!-- EMAIL FIELD -->
            <input type="text" class="form-control" id="loginId" placeholder="Email" name="usermail">

          </div>
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fas fa-lock"></i></div>
            </div>
            <!-- PASSWORD FIELD -->
            <input type="password" class="form-control" id="password" placeholder="Password" name="userword">
          
          </div>
 
          <button type="submit" class="btn btn-primary btn-lg btn-block login_btn"  style="background-color: #0064ff; border-color:#0064ff ;">
            <i class="fas fa-spinner fa-spin"></i>
            <span class="button_title">Log In</span>
          </button>

        </form>

        <div class="forgot_pwd_div">
          Or <a href={% url 'reset_password' %}>Forget Password Or Username</a>
        </div>
        <div>
          Don't have an account? <a href="{% url 'home:user_signuppage' %}">Sign up</a>   
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block add_js %}
<script src="/static/Js/user-side-js/user_login/login.js"></script>
{% endblock %}

zaptayfresh/templates/user_templates/user_login/user_signup.html
{% extends "user_templates/base_user.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block add_css %}
<link rel="stylesheet" href="/static/css/user-side-CSS/user_login/login.css">
{% endblock %}


{% block content %}
<div class="container">
  <div class="login_form_section">
    <div class="login_form_div">
      <h4 class="text-primary">Log In to your Zaptay Account</h4>
      <hr />
      <!-- <button type="button" class="btn btn-primary">Primary</button> -->
      <div class="login_form">
        <!--  -->




               <h2 class="text-success text-center">{{db_error}}<br>{{error}}<br>{{error2}}<br>{{A}}<br>{{not_match}}</h2> 
        {% comment %} <form method="POST" action="{% url 'home:user_signuppage' %}"> {% endcomment %}
       <form method="POST" action="{% url 'home:user_signuppage' %}">
          {% csrf_token %}

          <div class="alert alert-danger alert-dismissible fade" role="alert">
            <strong class="error_title">Holy guacamole!</strong> <span class="error_message"></span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fas fa-user"></i></div> 
            </div>
            <!-- EMAIL FIELD -->
            <input type="text" class="form-control" id="fname" placeholder="Full Name" name="fname">

          </div>

          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="far fa-envelope"></i></div>
            </div>
            <!-- EMAIL FIELD -->
            <input type="email" class="form-control" id="email" placeholder="Email" name="email">

          </div>

          {% comment %} <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fas fa-phone-alt"></i></div>
            </div>
             <!-- EMAIL FIELD -->
            <input type="number" class="form-control" id="loginId" placeholder="Phone No" name="pno"> 

          </div>{% endcomment %}
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fas fa-lock"></i></div>
            </div> 
            <!-- PASSWORD FIELD -->
            <input type="password" class="form-control" id="password" placeholder="Password" name="pwd">
          
          </div>
           <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fas fa-lock"></i></div>
            </div> 
            <!-- PASSWORD FIELD -->
            <input type="password" class="form-control" id="password2" placeholder="Re Enter Password" name="pwd2">
          
          </div>


          <!-- <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fas fa-lock"></i></div>
            </div>
            
            <input type="password" class="form-control" id="password" placeholder="Password" name="pwd">
          
          </div> -->
        
          <button type="submit" class="btn btn-primary btn-lg btn-block login_btn"  style="background-color: #0064ff; border-color:#0064ff ;">
            <i class="fas fa-spinner fa-spin"></i>
            <span class="button_title">Sign Up</span>
          </button>

        </form>

        <div class="forgot_pwd_div">
          Or <a href="">Forget Password</a>
        </div>
        <div>
          Have an account already ? <a href="{% url 'home:user_loginpage' %}">Log In</a>   
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block add_js %}
<script src="/static/Js/user-side-js/user_login/login.js"></script>
{% endblock %} 